### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by prayank23** [ACINQ/bitcoin-kmp#14]
Any link to read more about usage of this library with different examples?

If I create a sample Android app in which a transaction is created from scratch by using transaction id, outputs, amounts, fees etc. How would it work using this library?

Later how can I sign it and then broadcast it using local full node (bitcoin core) ?

**Comment by t-bast** [comment]
You simply create a `Transaction` object.
Have a look at the tests for guidance: https://github.com/ACINQ/bitcoin-kmp/tree/master/src/commonTest/kotlin/fr/acinq/bitcoin

**Comment by prayank23** [comment]
Thanks @t-bast
