### ISSUE TITLE
How can I verify message with bitcoinjs-message

### ISSUE THREAD

**Issue by vuongpsht** [ACINQ/bitcoin-kmp#29]
Description

I using Crypto.sign to generate the signature
but when I verify it with bitcoinjs-message, its not equal

**Comment by t-bast** [comment]
`Crypto.sign` simply produces an ECDSA signature that's valid inside bitcoin script.
This is *not* bitcoin's `signmessage` (https://bitcoincore.org/en/doc/0.21.0/rpc/wallet/signmessage/).

**Comment by vuongpsht** [comment]
> `Crypto.sign` simply produces an ECDSA signature that's valid inside bitcoin script.
> This is _not_ bitcoin's `signmessage` (https://bitcoincore.org/en/doc/0.21.0/rpc/wallet/signmessage/).

thank you for your reply, so do we have anyway to `signmessage`?

**Comment by t-bast** [comment]
No this isn't supported in `bitcoin-kmp`, we haven't needed it yet.
If you need it feel free to submit a PR though!

**Comment by vuongpsht** [comment]
> No this isn't supported in `bitcoin-kmp`, we haven't needed it yet.
> If you need it feel free to submit a PR though!

Thank you for supporting I still learning on this, when I have enough knowledge I will create PR for it 🤭🤭
