### ISSUE TITLE
Enable MacOS, WatchOS and tvOS platforms

### ISSUE THREAD

**Issue by goncalo-frade-iohk** [ACINQ/bitcoin-kmp#44]
Hi.

So I was wondering if there is a chance to enable this in the library.
From a look into the library I believe your iOS code doesn't need any change and there is just the need to add this platforms to your build.gradle.kts.

watchOS | watchosArm32, watchosArm64, watchosX86, watchosX64, watchosSimulatorArm64
tvOS | tvosArm64, tvosX64, tvosSimulatorArm64
macOS | macosX64, macosArm64

Have you tried this and is there an issue?

**Comment by sstone** [comment]
We haven't tried yet, but we would need to make https://github.com/ACINQ/secp256k1-kmp available on these platforms and there may be issues with arm targets.

**Comment by goncalo-frade-iohk** [comment]
Oh I see. Well iOS is arm64 since a long time, just the iOS simulator was x86_64.

Mac is actually playing catch up at this point with the new M1's.

So if you guys have problems with macosx64 just activating the macosArm64 should work I think (same for Apple TV and Watch OS).

FYI you can also enable the iosSimulatorArm64. As apparently it's not added when you just target 'ios'. I went to do some digging.

**Comment by t-bast** [comment]
If that's a feature that's useful to you, feel free to open a PR for it!

**Comment by goncalo-frade-iohk** [comment]
Perfect will do so :)

**Comment by jensmoes** [comment]
> Perfect will do so :)

Did you have any luck with iosSimulatorArm64 yet?
I have the same issue, converted my KMM project to support it, but now I am stuck being unable to use this project. Not quite sure what the issue is. But probably related to me not understanding the nitty gritty of gradle plays a large role :)

**Comment by sstone** [comment]
We support macos (x64 and arm64) and iosSimulatorArm64, but we don't have plans to support WatchOS and tvOS.
