### ISSUE TITLE
Add signet genesis block to Block.kt

### ISSUE THREAD

**Issue by remyers** [ACINQ/bitcoin-kmp#60]
To cleanly add signet support to Eclair to address  [topic# 2382](https://github.com/ACINQ/eclair/discussions/2382) we need to add the signet genesis block to Block.kt in bitcoin-kmp.

The genesis block for Signet is described in the wiki entry for [BIP 0325](https://en.bitcoin.it/wiki/BIP_0325#Genesis_Block).

The hash should be `00000008819873e925422c1ff0f99f7cc9bbb232af63a077a480a3633bee1ef6` (see similar definition in c-lightning [here](https://github.com/rustyrussell/lightning/blob/5ac88cef90ef210fc9e12b3696a9f9507fe83fe6/bitcoin/chainparams.c#L85)).

**Comment by sstone** [comment]
closed by https://github.com/ACINQ/bitcoin-kmp/pull/61
