### ISSUE TITLE
TLV

### ISSUE THREAD

**Issue by straumat** [ACINQ/bitcoin-kmp#79]
Hello, I'm working on Taro with a Java project. They "compress" some information and I need to decompress them. I asked them on their  discord and they replied that : "it’s raw bytes encoded w/ TLV"

Their code is here [decode](https://github.com/lightninglabs/taro/blob/77b69191fc60c57135c70e25b338d5d401bfbb2b/asset/encoding.go#L264). 

Does your library provides those methods?

**Comment by t-bast** [comment]
TLV isn't a compression mechanism, it's simply a binary encoding mechanism.
It is specified [here](https://github.com/lightning/bolts/blob/master/01-messaging.md#type-length-value-format).
As it is a lightning concept, not a bitcoin one, you won't find it in this library.
But we do have full support for tlv streams in [lightning-kmp](https://github.com/acinq/lightning-kmp), you should be able to work with that.
