### ISSUE TITLE
SegWit transactions lead to invalid signature error

### ISSUE THREAD

**Issue by MD9001** [ACINQ/bitcoin-kmp#89]
While trying to push transaction to main net, it results with "Code: -26, Error: non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation)".

PrivateKey is valid and generating public address using #PrivateKey.publicKey() results in the same address.
Previous Output scripts also have same public key hash.

Most probably I made a mistake somewhere, I would be glad, if you will help me with this matter.

`

        val previousTx = Transaction.read(prev_tx)
        val privateKey = PrivateKey.fromBase58(wif!!, Base58.Prefix.SecretKey).first

        val outScriptType = BtcScript.fromAddress(to) ?: error("Bad to address")
        val outHash = outScriptType.getHash(to)
        val outScript = outScriptType.createScriptPubKey(outHash)

        val out = ArrayList<TxOut>()
        out.add(TxOut(amount, outScript))

        val tx = Transaction(
            version = 1L,

            txIn = listOf(
                TxIn(OutPoint(previousTx.hash, 0), EMPTY_SEQUENCE)
            ),

            txOut = out,

            lockTime = 0L
        )

        val sig = Transaction.signInput(tx, 0, previousTx.txOut[0].publicKeyScript, SIGHASH_ALL, previousTx.txOut[0]
            .amount, SigVersion.SIGVERSION_WITNESS_V0, privateKey)

        val signedTx = tx.updateWitness(0, ScriptWitness()
            .push(sig)
            .push(privateKey.publicKey().value)
        )

        Transaction.validate(signedTx)
        Transaction.correctlySpends(signedTx, listOf(previousTx), ScriptFlags.MANDATORY_SCRIPT_VERIFY_FLAGS)

        return signedTx
    }`

**Comment by sstone** [comment]
To be 100% sure I would need to see the tx that you're spending from (or at least the tx output) but assuming that you're spending a p2wpkh output, the public key script that you're using to call `Transaction.signInput()` should not be `previousTx.txOut[0].publicKeyScript`. It should be `Script.pay2pkh("your pubkey here")`, see https://github.com/ACINQ/bitcoin-kmp/blob/master/src/commonTest/kotlin/fr/acinq/bitcoin/SegwitTestsCommon.kt#L171. It's one of the subtleties of segwit :)

**Comment by sstone** [comment]
For details about p2wpkh signing you can look at https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki#specification
p2wpkh is a special case, p2wsh works very much like ps2h, you can check https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki#specification for more examples.
